### ISSUE TITLE
StatsD metric flush timer changes in #489 are much worse

### ISSUE THREAD

**Issue by bmhatfield** [etsy/statsd#574] opened 2016-05-05 17:21 UTC
Related to https://github.com/etsy/statsd/pull/489 by @thomasmuehlschlegel

We were experiencing "drift" problems where we lost metrics on a periodic interval, as Thomas referenced. However, since upgrading to the newest Statsd (we were on 0.6.0 prior, now are on ~master), our metric drop-out rate is *dramatically* worse.

Here's a screenshot that illustrates what I mean:

![image](https://cloud.githubusercontent.com/assets/1119967/15050672/22d8d328-12c3-11e6-8694-e12890d5734d.png)

Please note that this metric should follow the curve on the left. Where the significant noise/drop-outs on the metric begin is where we updated to master.

Here's another, slightly harder to interpret screenshot to illustrate this point differently:

![image](https://cloud.githubusercontent.com/assets/1119967/15050755/8ac747e4-12c3-11e6-9811-020ad003fdee.png)

Around 14:00 (where the drop-out in the blue metric bar is, when we changed statsd versions), you can see the blue bar becomes *much* noisier, with lots of "partial values" for that minute.

**Comment by pathzzrd** [comment] 2016-05-05 19:20
@bmhatfield I just looked through our metrics and we've only had ~one dropped bucket since we deployed the patch to our cluster. That's not to say that this isn't an issue, just that I can't see it within our setup. I was about to take the current master and push it to npm but I'm not convinced that is a good idea looking at these images...

Can you share some more about the graphs we're seeing and your statsd configuration? Anything that could help us try and reproduce this issue would be incredibly helpful.

**Comment by bmhatfield** [comment] 2016-05-05 19:31
Happy to:

```
$ nodejs -v
v5.2.0
```

`Linux HOSTNAME 3.2.0-98-virtual #138-Ubuntu SMP Mon Jan 11 13:03:25 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux` (Ubuntu 12.04)

```
$ cat /etc/statsd/localConfig.js
{
  "flushInterval": 60000,
  "address": "127.0.0.1",
  "port": 8125,
  "mgmt_address": "127.0.0.1",
  "mgmt_port": 8126,
  "backends": [
    "./backends/graphite"
  ],
  "graphitePort": 2003,
  "graphiteHost": "GRAPHITEFQDN",
  "percentThreshold": [
    90,
    95,
    99
  ]
}
```

**Comment by bmhatfield** [comment] 2016-05-05 19:40
I am experiencing these drops on a system with *very* high statsd metric load - millions of individual points are sent to graphite per minute, which are then aggregated and flushed to Graphite once per minute.

Here's a graph with some interesting additional information, notably, prior to the upgrade these drops were simply a missing datapoint, now these drops are reported as 0s:

![metric-drops](https://cloud.githubusercontent.com/assets/1119967/15054870/9fe06444-12d7-11e6-9f1f-28d4981fcf7b.png)

**Comment by bmhatfield** [comment] 2016-05-05 19:40
Each host is running a local statsd which flushes to graphite, rather than a central statsd.

**Comment by draco2003** [comment] 2016-05-05 19:42
Are all metrics unique per statsd instance?

**Comment by bmhatfield** [comment] 2016-05-05 19:42
IE; do the metrics collide with each other on the Graphite server? No, with the one exception of the internal statsd performance metrics that it reports, but we don't (can't) use those because they don't have a prefix.

All other paths we flush have a hostname prefixed.

**Comment by pathzzrd** [comment] 2016-05-05 20:20
@bmhatfield could you try adding the top level configuration key `deleteIdleStats: true`, this should make it so that statsd doesn't write 0's for when it is missing data. I have a feeling this will work :)

Also I'm not sure how your are provisioning these statsd instances but on the newest master you can add another top level config key `prefixStats: "<some unique identifier>"` which will prefix the internal statsd perf metrics

**Comment by bmhatfield** [comment] 2016-05-06 15:34
Trying that out right now. I think the behavior I am looking to "get back to" is `deleteTimers`, since counts used to just send 0. It's still unclear to me why we're "missing" sends intermittently though. I will share more data once this is live.

**Comment by bmhatfield** [comment] 2016-05-06 16:34
Okay, after setting `deleteTimers: true`, timer metrics are visually similar to how they were before. It doesn't make sense for us to set `deleteCounters: true`, since `0` is a sensible value for some of our counters.

The thing I am not understanding here is *why* as of the current version statsd very frequently thinks these definately-not-idle metrics are idle? There's series with hundreds of thousands of values per flushInterval that seem to be interpreted as idle (either a 0 sent, or the series is not sent, depending on type/config).

Though this is not desired behavior (weird metric gaps), it is possible that it could be related to something other than the flushInterval timing behavior change. Looking back to see when the `deleteTimers` default was changed, that looks to have happened in 2013, so we were previously running a very old version of statsd, with a decent number of commits between then and now.

**Comment by pathzzrd** [comment] 2016-05-06 16:37
@bmhatfield maybe it is somehow related to #551, however I have been unable to reproduce this bug

**Comment by bmhatfield** [comment] 2016-05-06 16:38
Was just going to comment the same thing. Hopefully I should have statistics for you soon about the load (packets/metrics) these statsd processes are under to try and help illustrate that side better. I will also TCPdump and see if it's true that we're sending weird extra flushes.

**Comment by bmhatfield** [comment] 2016-05-06 17:19
Some statsd statistics to share (amusingly, the statsd internal statistics are also falling afoul of whatever this bug is):

![statsd-metrics-per-one-box](https://cloud.githubusercontent.com/assets/1119967/15080604/04cf10c0-138d-11e6-84ff-40c64cb4c57c.png)

I'm currently watching to see if I also see the "immediately writes a 0" bug or not. It's pretty intermittent it seems.

**Comment by bmhatfield** [comment] 2016-05-06 17:23
Okay, we're definitely hitting the same bug.

Normal:
```
stats.gusset.gusset2001.filters.deviceinfo.writes 3256.866666666667 1462555235
stats_counts.gusset.gusset2001.filters.deviceinfo.writes 195412 1462555235
```

Weird:
```
stats.gusset.gusset2001.filters.deviceinfo.writes 3252.55 1462555295
stats_counts.gusset.gusset2001.filters.deviceinfo.writes 195153 1462555295
stats.gusset.gusset2001.filters.deviceinfo.writes 0 1462555296
stats_counts.gusset.gusset2001.filters.deviceinfo.writes 0 1462555296
```

**Comment by bmhatfield** [comment] 2016-05-06 17:24
I noticed that we wrote out 0s for many series at the same time - including the internal `statsd` `packets_received` & `metrics_received` series.

**Comment by bmhatfield** [comment] 2016-05-06 17:28
I've also noticed that we'll *sometimes* also not perform a properly timed flush 1-2 minutes after this condition is hit. Sometimes we also hit this condition two consecutive minutes in a row, other times not for ~40m.

![metric-drops](https://cloud.githubusercontent.com/assets/1119967/15080944/6ff5eef4-138e-11e6-8ef1-50a0aa7a9213.png)

**Comment by bmhatfield** [comment] 2016-05-06 18:46
Okay, there's some bug with `getFlushTimeout()` that's leading to this:

```
6 May 18:00:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:01:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:02:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59996;  } INFO
6 May 18:03:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:04:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:05:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:06:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59998;  } INFO
6 May 18:07:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:08:14 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 1;  } INFO
6 May 18:08:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59122;  } INFO
6 May 18:09:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:10:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:11:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:12:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59997;  } INFO
6 May 18:13:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:14:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:15:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:16:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:17:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:18:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59989;  } INFO
6 May 18:19:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:20:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59998;  } INFO
6 May 18:21:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:22:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:23:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:24:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:25:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:26:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:27:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:28:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59998;  } INFO
6 May 18:29:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:30:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:31:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:32:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:33:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:34:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:35:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:36:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:37:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59994;  } INFO
6 May 18:38:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:39:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:40:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:41:14 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 1;  } INFO
6 May 18:41:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59174;  } INFO
6 May 18:42:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:43:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 59999;  } INFO
6 May 18:44:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
6 May 18:45:15 - getFlushTimeout(60000) { startup_time: 1462557255, flushInterval: 60000; returning: 60000;  } INFO
```

**Comment by bmhatfield** [comment] 2016-05-06 18:55
This "when is my next flush" method seems much more complicated than is necessary. I'm looking at how it can be simplified; I think this `1` return value is happening because the math/mod isn't working out the way the author expected.

**Comment by pathzzrd** [comment] 2016-05-06 19:17
Following along on mobile right now. Thanks for diving into this. Just
brain dumping here. iirc we just merged #489 on 3/31 and this bug first
popped up in the issues stream some time in November. Not ruling our the
timer changes as a cause, but there is likely some other bug that
contributes to this as well.

At Etsy our buckets are only 10s so It's entirely possible that this might
only show up for statsd instances configured with larger flushIntervals.

**Comment by bmhatfield** [comment] 2016-05-06 20:58
Here's a snapshot of the math that I logged while trying to diagnose what is up here:

```
6 May 20:18:06 - 60000 - (1462565886001 - 1462561086 * 1000)[= 4800001] % 60000
6 May 20:18:06 - getFlushTimeout(60000) { time: 1462565886001, startup_time: 1462561086, flushInterval: 60000; returning: 59999;  } INFO

6 May 20:19:06 - 60000 - (1462565946003 - 1462561086 * 1000)[= 4860003] % 60000
6 May 20:19:06 - getFlushTimeout(60000) { time: 1462565946003, startup_time: 1462561086, flushInterval: 60000; returning: 59997;  } INFO

6 May 20:20:05 - 60000 - (1462566005999 - 1462561086 * 1000)[= 4919999] % 60000
6 May 20:20:06 - getFlushTimeout(60000) { time: 1462566005999, startup_time: 1462561086, flushInterval: 60000; returning: 1;  } INFO

So, that's fun.

![screen shot 2016-05-06 at 4 57 38 pm](https://cloud.githubusercontent.com/assets/1119967/15085974/b00410f8-13ab-11e6-8179-384caa1a2036.png)

```

**Comment by bmhatfield** [comment] 2016-05-07 00:21
Okay, after studying these numbers for a while, I think the problem is that this approach assumes the call coming in from setTimeout will always be on time (60000ms later) or late (by some milliseconds), but in my environment it's sometimes actually *early* by wallclock time. These systems are running in EC2, so it's possible virtualized clocks are getting the best of us here.

I'm thinking of the best way to deal with this given the desire to use wall-clock time to deal with other forms of drift in JS, and I will put up a PR when I figure it out.

**Comment by pathzzrd** [comment] 2016-05-07 00:28
Was looking around online today and saw this snippet on stackoverflow:
http://stackoverflow.com/a/29972322

Stackoverflow aside It's likely a good starting point.

**Comment by bmhatfield** [comment] 2016-05-07 00:35
One stupid but easy option would be to just put the `setTimeout(flushMetrics, getFlushTimeout(flushInterval));` call at the end of `flushMetrics` rather than the beginning to try and make sure we always come in "late", which is one of the things noted in the SO example you shared.

I'll try that and see if it makes any difference.

**Comment by bmhatfield** [comment] 2016-05-07 00:41
This almost certainly will work. I'll let it run for a while, but by putting it at the end of the method, I am looking at 400-500ms of delay instead of 0-1ms, which is plenty more than enough to make sure we never stumble into this clock-skew-race-weird-condition.

**Comment by bmhatfield** [comment] 2016-05-07 00:57
Here's a PR: https://github.com/etsy/statsd/pull/575

**Comment by pathzzrd** [comment] 2016-05-07 01:33
Excellent I'll look to merge this soon. Again, thank you very much.

**Comment by bmhatfield** [comment] 2016-05-07 02:17
Just rolled this out in production (via my branch)... this stacked graph has never looked so clean:

![stacked-graph-example](https://cloud.githubusercontent.com/assets/1119967/15089717/40da0070-13d8-11e6-984b-f5441d8c70cb.png)

**Comment by pathzzrd** [comment] 2016-05-09 16:29
Just merged the patch, going to push this to our production metrics cluster soon.

**Comment by pathzzrd** [comment] 2016-05-11 19:14
Looks stable :)

Thanks again @bmhatfield !

**Closed by pathzzrd** 2016-05-11 19:14 UTC
