### ISSUE TITLE
"timing" has nothing to do with timing

### ISSUE THREAD

**Issue by Dieterbe** [etsy/statsd#98] opened 2012-06-11 11:16 UTC
the metric type "timing" has a misleading choice of a name, because it doesn't have anything to do with timings per se (although timings may be a common, or even the most common use of it).

fundamentally, this metric takes multiple numbers in a short time interval, and calculates the avg/percentile/min/max. that's it.

let's try to devise a better name.
here's a suggestion: `analyzer` (or `interval-analyzer` but the fact that it operates on a time interval is fairly obvious as statsd is an aggregator, and can be explained in the metric type's documentation)

**Comment by mrtazz** [comment] 2015-01-22 15:53
Closing this since the issue is super old and we haven't found a better name. And timing has served us well in the past years.

**Closed by mrtazz** 2015-01-22 15:53 UTC
